# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: synse-emulator-plugin
before:
  hooks:
    - make clean
    - go get -u github.com/golang/dep/cmd/dep
    # you may remove this if you don't use vgo
    - dep ensure
builds:
- env:
  - CGO_ENABLED=0
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums-{{ .Tag }}.txt'
release:
  github:
    owner: lazypower
    name: synse-emulator-plugin
  draft: true
  prerelease: auto
  name_template: "{{.ProjectName}}-v{{.Version}} {{.Env.USER }}"
dockers:
  -
   goos: linux
   goarch: amd64
   binaries:
     - synse-emulator-plugin
   image_templates:
    - vaporio/synse-emulator-plugin:{{ .Tag }}
    - vaporio/synse-emulator-plugin:{{ .Major }}
    - vaporio/synse-emulator-plugin:{{ .Major }}.{{ .Minor }}
    - vaporio/synse-emulator-plugin:latest
   build_flag_templates:
    - "--label=org.label-schema.schema-version=1.0"
    - "--label=org.label-schema.version={{.Version}}"
    - "--label=org.label-schema.build-date={{.Date}}"
    - "--label=org.label-schema.name=vaporio/emulator-plugin"
    - "--label=org.label-schema.vcs-url=https://github.com/vapor-ware/synse-emulator-plugin"
    - "--label=org.label-schema.vcs-ref={{.ShortCommit}}"
    - "--label=org.label-schema.vendor=Vapor IO"
   extra_files:
    - bin
    - config
    - config.yml
    - Gopkg.lock
    - Gopkg.toml
    - main.go
    - Makefile
    - pkg
    - vendor
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
