# For details, see the GoReleaser documentation at http://goreleaser.com
project_name: synse-emulator-plugin
before:
  hooks:
    - go clean -v
    - rm -rf dist
builds:
- env:
  - CGO_ENABLED=0
  ldflags:
  - -w
  - -X github.com/vapor-ware/synse-emulator-plugin/vendor/github.com/vapor-ware/synse-sdk/sdk.BuildDate={{ .Date }}
  - -X github.com/vapor-ware/synse-emulator-plugin/vendor/github.com/vapor-ware/synse-sdk/sdk.GitCommit={{ .ShortCommit }}
  - -X github.com/vapor-ware/synse-emulator-plugin/vendor/github.com/vapor-ware/synse-sdk/sdk.GitTag={{ .Tag }}
  - -X github.com/vapor-ware/synse-emulator-plugin/vendor/github.com/vapor-ware/synse-sdk/sdk.GoVersion={{ .Env.GOVERSION }}
  - -X github.com/vapor-ware/synse-emulator-plugin/vendor/github.com/vapor-ware/synse-sdk/sdk.PluginVersion={{ .Version }}
  goos:
  - linux
  - darwin
  goarch:
  - amd64
archive:
  format: tar.gz
checksum:
  name_template: 'checksums-{{ .Tag }}.txt'
release:
  github:
    owner: vapor-ware
    name: synse-emulator-plugin
  draft: false
  prerelease: auto
  name_template: "{{ .Version }}"
dockers:
  -
   goos: linux
   goarch: amd64
   binaries:
     - synse-emulator-plugin
   image_templates:
    - vaporio/emulator-plugin:{{ .Tag }}
    - vaporio/emulator-plugin:{{ .Major }}
    - vaporio/emulator-plugin:{{ .Major }}.{{ .Minor }}
    - vaporio/emulator-plugin:latest
   build_flag_templates:
    - "--label=org.label-schema.schema-version=1.0"
    - "--label=org.label-schema.version={{ .Version }}"
    - "--label=org.label-schema.build-date={{ .Date }}"
    - "--label=org.label-schema.name=vaporio/emulator-plugin"
    - "--label=org.label-schema.vcs-url=https://github.com/vapor-ware/synse-emulator-plugin"
    - "--label=org.label-schema.vcs-ref={{ .ShortCommit }}"
    - "--label=org.label-schema.vendor=Vapor IO"
   extra_files:
    - config/device
    - config.yml
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
