version: 3
debug: true
id:
  useMachineID: false
network:
  type: tcp
  address: ":5001"
settings:
  mode: parallel
  # for the sake of example, the read and write intervals
  # are set to different values, though they would be fine
  # if set to the same value.
  read:
    interval: 1s
  write:
    interval: 2s
  cache:
    enabled: true
    ttl: 5m
