version: 1.0
debug: true
network:
  type: unix
  address: emulator.sock
settings:
  mode: parallel
  # for the sake of example, the read and write intervals
  # are set to different values, though they would be fine
  # if set to the same value.
  read:
    interval: 1s
  write:
    interval: 2s