# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.

[[constraint]]
  name = "github.com/vapor-ware/synse-sdk"
  version = "3.0.0-alpha.1"

[prune]
  go-tests = true
  unused-packages = true
