# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.

[[constraint]]
  name = "github.com/vapor-ware/synse-sdk"
  branch = "v3/stream-poc"

[prune]
  go-tests = true
  unused-packages = true
