version: 3
devices:
  - type: status
    context:
      emulated: true
      model: Vapor Carousel
    instances:
      - info: Carousel Get Rack Position
        data:
          id: 1
      - info: Carousel Set Rack Position
        data:
          id: 2
      - info: Carousel State Machine Code
        data:
          id: 3
      - info: Carousel Status Register
        data:
          id: 4
      - info: Carousel VFD Error Code
        data:
          id: 5

  - type: json
    context:
      emulated: true
      model: Vapor Carousel
    instances:
      - info: Carousel Rotate
        data:
          id: 6
