version: 3
devices:
  - type: led
    metadata:
      model: emul8-led
    instances:
      - info: Synse LED
        data:
          id: 1
      - info: Synse Backup LED
        data:
          id: 2
