version: 3
devices:
  - type: power
    context:
      model: emul8-power
    instances:
      - info: Zone 1 Power
        data:
          id: 1
      - info: Zone 2 Power
        data:
          id: 2
      - info: Zone 3 Power
        data:
          id: 3
      - info: Zone 4 Power
        data:
          id: 4
      - info: Total Power Usage
        data:
          id: 5

  - type: voltage
    context:
      model: emul8-voltage
    instances:
      - info: Zone 1 Voltage
        data:
          id: 1
      - info: Zone 2 Voltage
        data:
          id: 2

  - type: energy
    context:
      model: emul8-energy
    instances:
      - info: Zone 1 Kilowatt-hour
        data:
          id: 1
      - info: Zone 2 Kilowatt-hour
        data:
          id: 2

