version: 1.0
locations:
  - name: r1vec
    rack:
      name: rack-1
    board:
      name: vec
devices:
  - name: power
    metadata:
      model: emul8-power
    outputs:
      - type: power
    instances:
      - info: Zone 1 Power
        location: r1vec
        data:
          id: 1
      - info: Zone 2 Power
        location: r1vec
        data:
          id: 2
      - info: Zone 3 Power
        location: r1vec
        data:
          id: 3
      - info: Zone 4 Power
        location: r1vec
        data:
          id: 4
      - info: Total Power Usage
        location: r1vec
        data:
          id: 5
