version: 3
devices:
  - type: pressure
    metadata:
      model: emul8-pressure
    instances:
      - info: Synse Pressure Sensor 1
        data:
          id: 1
      - info: Synse Pressure Sensor 2
        data:
          id: 2
