version: 3
devices:
  - type: temperature
    context:
      model: emul8-temp
    instances:
      - info: Synse Temperature Sensor 1
        data:
          id: 1
      - info: Synse Temperature Sensor 2
        data:
          id: 2
      - info: Synse Temperature Sensor 3
        data:
          id: 3
      - info: Synse Temperature Sensor 4
        data:
          id: 4
      - info: Synse Temperature Sensor 5
        data:
          id: 5
